devtest/urls.py
from django.conf.urls import include, url
from django.contrib import admin

urlpatterns = [
    url(r'^trades/', include('trades.urls')),
    url(r'^admin/', admin.site.urls),
]

trades/urls.py
from django.conf.urls import url

from . import views

app_name = 'trades'
urlpatterns = [
    url(r'^$', views.index, name='index'),
    url(r'^new_trade/$', views.new_trade, name='new_trade'),
    url(r'^update_trade/$', views.update_trade, name='update_trade'),
]

trades/models.py
# -*- coding: utf-8 -*-
from __future__ import unicode_literals
from django.db import models
import uuid


BASE62 = "0123456789abcdefghijklmnopqrstuvwxyzABCDEFGHIJKLMNOPQRSTUVWXYZ"
def encode(num, alphabet=BASE62):
    """Encode a positive number in Base X
    Arguments:
    - `num`: The number to encode
    - `alphabet`: The alphabet to use for encoding
    """
    if num == 0:
        return alphabet[0]
    arr = []
    base = len(alphabet)
    while num:
        num, rem = divmod(num, base)
        arr.append(alphabet[rem])
    arr.reverse()
    return ''.join(arr)


def decode(string, alphabet=BASE62):
    """Decode a Base X encoded string into the number
    Arguments:
    - `string`: The encoded string
    - `alphabet`: The alphabet to use for encoding
    """
    base = len(alphabet)
    strlen = len(string)
    num = 0
    idx = 0
    for char in string:
        power = (strlen - (idx + 1))
        num += alphabet.index(char) * (base ** power)
        idx += 1
    return num




class Trade(models.Model):
    # having a database id like this is bad
    # there are multiple options that would be more easy and eficient to deal with.
    id = models.CharField(max_length=9, primary_key=True)
    sell_currency=models.CharField(max_length=200)
    sell_amount=models.FloatField()
    buy_currency=models.CharField(max_length=200)
    buy_amount=models.FloatField()
    rate=models.FloatField()
    date_booked=models.DateTimeField('date booked', auto_now_add=True)
    
    
    # I would prefer storing in the database a plain integer 
    # that is eventually converted to alphanumeric if needed
    # If the code is used to define entries I may needed here to query
    def new_id(self):
        num = Trade.objects.filter(id__startswith = 'TD').count()
        return 'TD'+encode(num).zfill(7)
    
 

trades/forms.py
from django import forms
from .models import Trade
import fixerio



aux = fixerio.Fixerio()
rates = aux.latest()
rates= rates['rates']
rates = ((' ', ' ',),) + tuple([(key,key,) for key,val in rates.iteritems()])



class TradeForm(forms.Form):
    class Meta:
        model = Trade
        fields = ( 'sell_currency', 
                   'sell_amount',
                   'buy_currency',
                   'buy_amount',
                   'rate')

    rate = forms.FloatField()
    sell_currency = forms.CharField(widget=forms.Select(choices=rates, attrs={'class': 'selectpicker'}))
    sell_amount = forms.FloatField() 
    buy_currency = forms.CharField(widget=forms.Select(choices=rates, attrs={'class': 'selectpicker'}))
    buy_amount = forms.FloatField()
    buy_amount.widget.attrs['readonly'] = True  
    rate.widget.attrs['readonly'] = True      
        
        

trades/views.py
# -*- coding: utf-8 -*-
from __future__ import unicode_literals

from django.http import HttpResponse
from django.http import JsonResponse
from django.http import HttpResponseRedirect

from django.shortcuts import render
from django.template import loader
from django.urls import reverse

from .models import Trade
from .forms import TradeForm

import fixerio



def index(request):
    template = loader.get_template('trades/index.html')
    context = {'trade_list': Trade.objects.all().order_by('-date_booked')}
    return HttpResponse(template.render(context, request))



def new_trade(request):
    if request.method == 'POST':
        form = TradeForm(request.POST, request.FILES)
        if form.is_valid():
            obj = Trade()
            obj.id = obj.new_id()
            obj.sell_currency=form.cleaned_data['sell_currency']
            obj.sell_amount=form.cleaned_data['sell_amount']
            obj.buy_currency=form.cleaned_data['buy_currency']
            obj.buy_amount=form.cleaned_data['buy_amount']
            obj.rate=form.cleaned_data['rate']
            obj.save()
            return HttpResponseRedirect(reverse('trades:index'))
    else:
        form = TradeForm()
    return render(request, 'trades/new_trade.html', {'form': form})


    
def update_trade(request):
    '''
    This will get the data from fixerio to update our UI.
    todo: we need here a loading screen - and timeout -  to block the UI until we get the data.
    '''
    data={'ratio': 1}
    sell_currency = request.GET.get('sell_currency', None)
    buy_currency = request.GET.get('buy_currency', None)
    if sell_currency and buy_currency:
        aux = fixerio.Fixerio()
        rates = aux.latest(base=sell_currency) 
        ratio = rates['rates'].get(buy_currency,1)
        data = {'ratio': ratio}
    return JsonResponse(data)

trades/templates/trades/index.html
{% load staticfiles %}

<link href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-BVYiiSIFeK1dGmJRAkycuHAHRg32OmUcww7on3RYdg4Va+PmSTsz/K68vbdEjh4u" crossorigin="anonymous"> 

{% block content %}
	<h1>Booked Trades</h1>
	
		<table border="0" width="100%">
			<tr>
				<td width="72%"></td>
				<td>
					<form method="POST" action="/trades/new_trade/">
						{% csrf_token %}
						<button type="submit" class="btn btn-primary"/>New Trade</button> 
					</form>
				</td>
			</tr>
		</table>
	
	{% if trade_list %}	
		<table class="table table-striped" border="0" width="100%">
			<tr>
				<th>Sell CCY</th>
				<th>Sell Amount</th>
				<th>Buy CCY</th>
				<th>Buy Amount</th>
				<th>Rate</th>
				<th>Date Booked</th>
			</tr>
			    {% for trade in trade_list %}
			    	<tr>
				    	<td>{{ trade.sell_currency }}</td>
				    	<td>{{ trade.sell_amount }}</td>
				    	<td>{{ trade.buy_currency }}</td>
				    	<td>{{ trade.buy_amount }}</td>
				    	<td>{{ trade.rate }}</td>
				    	<td>{{ trade.date_booked }}</td>
				    </tr>
				{% endfor %}
		 </table>
	{% else %}
		<p>No trades are available.</p>
	{% endif %}
{% endblock %}

trades/templates/trades/new_trade.html
{% load staticfiles %}

{% block javascript %}	
<link href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-BVYiiSIFeK1dGmJRAkycuHAHRg32OmUcww7on3RYdg4Va+PmSTsz/K68vbdEjh4u" crossorigin="anonymous">

<script language="javascript" type="text/javascript" src="https://code.jquery.com/jquery-3.3.1.min.js"></script> 
<script type="text/javascript">

		$(function() {
			$("#ajaxProgress").hide();
		  	$("#id_sell_currency").change( function () {
		  		$("#save_button").attr('disabled','disabled');
		  		$("#ajaxProgress").show();
		        $.ajax({
		        	url: '/trades/update_trade/',
		          	dataType: 'json',
		          	data: {
		            	'sell_currency':$("#id_sell_currency").val(),
		            	'buy_currency': $("#id_buy_currency").val()
		          	},
		          	success: function (data) {
		            	$('#id_rate').attr('value', data.ratio);
		            	$('#id_buy_amount').attr('value', data.ratio*$("#id_sell_amount").val());
		            	$("#save_button").removeAttr('disabled');
		            	$("#ajaxProgress").hide();
		          	}
		        });
		      });
		  
	    	$("#id_buy_currency").change( function () {
		  		$("#save_button").attr('disabled','disabled');
		  		$("#ajaxProgress").show();
	      		$.ajax({
	        		url: '/trades/update_trade/',
	        		dataType: 'json',
	        		data: {
	          			'sell_currency':$("#id_sell_currency").val(),
		            	'buy_currency': $("#id_buy_currency").val()
	        		},
	        		success: function (data) {
	            		$('#id_rate').attr('value', data.ratio);
	            		$('#id_buy_amount').attr('value', data.ratio*$("#id_sell_amount").val());
		            	$("#save_button").removeAttr('disabled');
		            	$("#ajaxProgress").hide();
	        		}
	      		});
	   		});
	   		
	    	$("#id_sell_amount").on('input', function(){ 
		  		$("#save_button").attr('disabled','disabled');
		  		$("#ajaxProgress").show();
	      		$.ajax({
	        		url: '/trades/update_trade/',
	        		dataType: 'json',
	        		data: {
	          			'sell_currency':$("#id_sell_currency").val(),
		            	'buy_currency': $("#id_buy_currency").val()
	        		},
	        		success: function (data) {
	            		$('#id_rate').attr('value', data.ratio);
	            		$('#id_buy_amount').attr('value', data.ratio*$("#id_sell_amount").val());
		            	$("#save_button").removeAttr('disabled');
		            	$("#ajaxProgress").hide();
	        		}
	      		});
	   		});
 		    	
		});
	</script>
{% endblock %}


{% block content %}
	<h1>New Trade</h1>
	
	<div class="content container">
		<div class="row">
			<div class="col-md-8">
            	<form method="POST" action="">

            		{% csrf_token %}
					<table border="0" width="100%">
						<tr>
      						<td>{{ form.sell_currency.label_tag }}</td>
      						<td>{{ form.rate.label_tag }}</td>
							<td>{{ form.buy_currency.label_tag }}</td>
    					</tr>
      					<tr>
        					<td>{{ form.sell_currency }} </td>
          					<td>&#9654 {{ form.rate }} &#9654 </td>
          					<td>{{ form.buy_currency }}</td>
      					</tr>
      					<tr>  
      						<td><hr /></td>
      						<td><hr /></td> 
      						<td><hr /></td>  
      					</tr>
      					<tr>
        					<td>{{form.sell_amount.label_tag }}</td>
        					<td></td>
							<td>{{form.buy_amount.label_tag }}</td>
      					</tr>  
      					<tr>
        					<td>{{form.sell_amount}}</td>
        					<td></td>
							<td>{{form.buy_amount}}</td>
      					</tr>
      					<tr>  
      						<td><hr /></td>
      						<td><hr /></td> 
      						<td><hr /></td>  
      					</tr>
      					<tr>
							<td><button class="btn btn-primary" type="submit" name="submit" id="save_button">Create</button></td>
							<td></td>
							<td><button class="btn btn-primary" type="reset" onclick="location.href = '{% url 'trades:index' %}';" name="cancel"  id="cancel_button" formnovalidate>Cancel</button></td>
      					</tr>
      				</table>

				</form>    			    
			</div>
		</div>
	</div>
	
	
	<div id="ajaxProgress">
		<p>Please Wait...</p>
	</div>
{% endblock %}